TASK_HEARTBEAT = "HEARTBEAT"
TASK_REGISTER = "REGISTER"
TASK_TASK_REQUEST = "TASK_REQUEST"
TASK_TASK_RESULT = "TASK_RESULT"
TASK_REDIRECT = "REDIRECT"
TASK_HELP_REQUEST = "HELP_REQUEST"
TASK_HELP_OFFER = "HELP_OFFER"
TASK_HELP_ACCEPT = "HELP_ACCEPT"
TASK_WORKER_RETURN = "WORKER_RETURN"

RESPONSE_ALIVE = "ALIVE"
RESPONSE_OK = "OK"

MESSAGE_DELIMITER = "\n"
